# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = ["blowfish", "hugo-simplecite"]
baseURL = "https://iam.fabiograsso.net/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "I_AM Fabio"
mainSections = ["posts", "blog", "tips", "travels", "howto", "kitchen"]

disableLanguages = [] #to allow translation work requiring shipping to production

summaryLength = 25
enableRobotsTXT = true
buildExpired = false
buildDrafts = false
buildFuture = false
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true

defaultFeaturedImage = "img/homebg.webp"

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Smart'
  quality = 80
  # hint = photo
  resampleFilter = "Lanczos"

[pagination]
  pagerSize = 20

[taxonomies]
  tag = "tags"
  # category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[services]
  [rss]
    limit = 42
    filename = "index.xml"
    section = "posts"
    includeHome = false
[permalinks]
  posts = "/:sections/:slugorcontentbasename/"
  section = "/:section/"
  about = "/about/"
  privacy = "/privacy/"
  contact = "/contact/"

[[cascade]]
  comments = true
  showComments = true
  ShowToc = true
  [cascade._target]
    kind = "page"
    section = "posts"

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "sections"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
