# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

# https://gohugo.io/configuration/markup/#highlight
[highlight]
  noClasses = false
  # anchorLineNos = false
  codeFences = true
  # guessSyntax = false
  # hl_Lines = ''
  # hl_inline = false
  lineAnchors = ''
  # lineNoStart = 1
  # lineNos = true
  # lineNumbersInTable = true
  #style = 'monokai'
  style = 'vim'
  #tabWidth = 2
  #wrapperClass = 'highlight'

[tableOfContents]
  startLevel = 2
  endLevel = 4