# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "Fire"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# robots = ""

copyright = """
  <span style="display: inline-block;">
    &copy; 2025 <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500" href="/about">Fabio Grasso</a>
  </span> - 
  <span style="display: inline-block;">
    License: <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500" rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>
  </span>
-
  <span style="display: inline-block;">
    <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500" href="/posts/index.xml">RSS</a>
  </span> - 
  <span style="display: inline-block;">
    <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500" href="/privacy">Privacy&Cookie Policy</a>
  </span>
  <br/>
  <span style="line-height: 1.3em; margin-top: 1em;">
    ✍️ Crafted with the help of 🤖 AI. <br/>
    💡 All content is fact-checked, edited, and reflects the author’s expertise and opinions.
  </span>
"""

#logo = "img/apple-touch-icon.png"
#secondaryLogo = "img/apple-touch-icon.png" # dark mode

#defaultBackgroundImage = "/img/hero2.svg"
#defaultFeaturedImage = "/img/featured.svg"
#defaultSocialImage = "/img/blowfish_banner.png"
highlightCurrentMenuArea = true


smartTOC = true
smartTOCHideUnfocusedChildren = false


[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, and fixed-fill-blur.

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true
  
[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/homebg.webp"
  showRecent = true
  showRecentItems = 20
  showMoreLink = true
  showMoreLinkDest = "/posts"
  layoutBackgroundBlur = true # only used when layout equals background
  # disableHeroImageFilter =
  showSummary = true
  #cardView = true

[article]
  showDate = true
  #showViews = true
  #showLikes = true
  showDateUpdated = false
  showAuthor = true
  showAuthorsBadges = true
  #showAuthorBottom=true
  showHero = true
  heroStyle = "big" # valid options: basic, big, background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/fabiograsso/iam-fabiograsso-net/tree/main/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showWordCount = true
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "facebook", "whatsapp", "telegram", "reddit", "email","line"]
  showZenMode = true
  showTaxonomies = true
#  showRelatedContent=true
  
[list]
  showHero = true
  # heroStyle = basic # basic, big, background, thumbAndBackground.
  showSummary = true

[taxonomy]
#  showHero = true
#  heroStyle = # basic, big, background, thumbAndBackground
  showTermCount = true
  showSummary = true

[term]
#  showHero = true
  showTermCount = true
  showSummary = true

[sitemap]
  excludedKinds = ["privacy"]


[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

# [RSSNext]
# feedId =
# userId =