services:

  hugo:
    image: docker.io/hugomods/hugo:std-exts
    working_dir: /src
    command: server --bind 0.0.0.0 --baseURL http://localhost --disableFastRender --logLevel debug -p ${HUGO_PORT:-1313}
    volumes:
      - ./:/src
    ports:
      - "${HUGO_PORT:-1313}:${HUGO_PORT:-1313}"
    networks:
      - hugonet

  decap-proxy:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=${DECAP_PORT:-1314}
      - GIT_REPO_DIRECTORY=/app
      - NODE_ENV=development
    command: sh -c "npx decap-server"
    ports:
      - "${DECAP_PORT:-1314}:${DECAP_PORT:-1314}"
    networks:
      - hugonet

networks:
  hugonet:
    driver: bridge
