baseURL = 'https://iam.fabiograsso.net'
languageCode = 'en-us'
title = 'IAM.FabioGrasso.net'
defaultContentLanguage = 'en'
theme = 'PaperMod'

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  hideSummary = true

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/english'
    weight = 1
    title = 'IAM.FabioGrasso.net'
    [languages.en.params]
      languageName = 'En' 
  [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Blog'
      url = '/en/posts/'

  [languages.it]
    languageName = 'Italiano'
    contentDir = 'content/italiano'
    weight = 2
    title = 'IAM.FabioGrasso.net'
    [languages.it.params]
      languageName = 'It' 
  [languages.it.menu]
    [[languages.it.menu.main]]
      name = 'Blog'
      url = '/it/posts/'

  [languages.fr]
    languageName = 'Français'
    contentDir = 'content/francais'
    weight = 3
    title = 'IAM.FabioGrasso.net'
    [languages.fr.params]
      languageName = 'Fr' 
  [languages.fr.menu]
    [[languages.fr.menu.main]]
      name = 'Blog'
      url = '/fr/posts/'