baseURL = 'https://iam.fabiograsso.net'
languageCode = 'en-us'
title = 'IAM.FabioGrasso.net'
defaultContentLanguage = 'en'
theme = 'PaperMod'

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/english'
    weight = 1
    title = 'IAM.FabioGrasso.net'

  [languages.it]
    languageName = 'Italiano'
    contentDir = 'content/italiano'
    weight = 2
    title = 'IAM.FabioGrasso.net'

  [languages.fr]
    languageName = 'Français'
    contentDir = 'content/francais'
    weight = 3
    title = 'IAM.FabioGrasso.net'



