backend:
  name: git-gateway
  branch: main

local_backend:
  url: http://localhost:1314/api/v1
  allowed_hosts: ['localhost']

media_folder: static/img
public_folder: /img

site_url: http://localhost:1313
#site_url: https://iam-fabiograsso-net.netlify.app/

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false  }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    nested:
      depth: 50
      summary: "{{title}}"
    # extension: "it.md"
    format: "frontmatter"
    meta:
      path:
        widget: "string"
        label: "Path (bundle folder)"
        index_file: "index"
    media_folder: "" 
    public_folder: ""
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", default: "" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, required: false  }
      - { label: "Description", name: "description", widget: "string", default: "A brief description.", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["tag-1", "tag-2", "tag-3"], required: false }
      - { label: "Categories", name: "categories", widget: "list", default: ["blog"], required: false }
      - { label: "translationKey", name: "translationKey", widget: "string", default: "intro-to-hugo", required: false }
      - { label: "toc", name: "toc", widget: "boolean", default: false }
      - { label: "Show Bread Crumbs", name: "ShowBreadCrumbs", widget: "boolean", default: true }
      - { label: "Show Reading Time", name: "ShowReadingTime", widget: "boolean", default: true }
      - { label: "Hide Summary", name: "hideSummary", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: "Fabio Grasso", required: false }
      - label: "Cover"
        name: "cover"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Image", name: "image", widget: "string", default: "/images/social-cover.jpg", hint: "Percorso relativo o assoluto" }
          - { label: "Alt", name: "alt", widget: "string", default: "Descrizione dell'immagine", required: false }
          - { label: "Caption", name: "caption", widget: "string", default: "Crediti immagine", required: false }
          - { label: "Relative", name: "relative", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
