name: Replace Acronyms

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  replace-acronyms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Acronym Replacement
        run: |
          import yaml, re, os

          # Load acronym dictionary
          with open("data/acronyms.yaml", "r") as f:
              acronyms = yaml.safe_load(f)

          def replace_acronyms(text):
              for term, definition in acronyms.items():
                  # Match the acronym only if not inside an <abbr> already
                  pattern = r'(?<!<abbr title="[^"]*">)\\b{}\\b(?!</abbr>)'.format(re.escape(term))
                  replacement = f'<abbr title="{definition}">{term}</abbr>'
                  text = re.sub(pattern, replacement, text)
              return text

          changed_files = []

          for root, dirs, files in os.walk("content/posts"):
              for file in files:
                  if file.endswith(".md"):
                      full_path = os.path.join(root, file)
                      with open(full_path, "r", encoding="utf-8") as f:
                          content = f.read()
                      new_content = replace_acronyms(content)
                      if content != new_content:
                          with open(full_path, "w", encoding="utf-8") as f:
                              f.write(new_content)
                          changed_files.append(full_path)

          if changed_files:
              print("Modified files:")
              for f in changed_files:
                  print(f)
          else:
              print("No acronym replacements needed.")

        shell: python

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-replace acronyms"
          git push
